/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#121222',
        'surface-dim': '#121222',
        'surface-bright': '#38374a',
        'surface-container-lowest': '#0c0c1d',
        'surface-container-low': '#1a1a2b',
        'surface-container': '#1e1e2f',
        'surface-container-high': '#29283a',
        'surface-container-highest': '#333345',
        'surface-variant': '#333345',
        'primary': '#ddb7ff',
        'primary-fixed': '#f0dbff',
        'primary-fixed-dim': '#ddb7ff',
        'primary-container': '#4b0082',
        'on-primary': '#4a0080',
        'on-primary-container': '#ba7ef4',
        'on-primary-fixed': '#2c0050',
        'on-primary-fixed-variant': '#622599',
        'inverse-primary': '#7b41b3',
        'secondary': '#c9a84c',
        'secondary-fixed': '#ffe08f',
        'secondary-fixed-dim': '#c9a84c',
        'secondary-container': '#785d00',
        'on-secondary': '#3d2e00',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',
        'on-secondary-container': '#fdd977',
        'tertiary': '#c8bfff',
        'tertiary-fixed': '#e5deff',
        'tertiary-fixed-dim': '#c8bfff',
        'tertiary-container': '#2d00a0',
        'on-tertiary': '#2d009d',
        'on-tertiary-fixed': '#190064',
        'on-tertiary-fixed-variant': '#442bb5',
        'on-tertiary-container': '#9989ff',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#978d9d',
        'outline-variant': '#4c4451',
        'background': '#121222',
        'on-background': '#e3e0f8',
        'on-surface': '#e3e0f8',
        'on-surface-variant': '#cec3d3',
        'inverse-surface': '#e3e0f8',
        'inverse-on-surface': '#2f2f40',
        'surface-tint': '#ddb7ff',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
