/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#000000',
        'surface-dim': '#000000',
        'surface-bright': '#1f1f1f',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#0a0a0a',
        'surface-container': '#111111',
        'surface-container-high': '#1a1a1a',
        'surface-container-highest': '#242424',
        'surface-variant': '#242424',
        'primary': '#6DB36D',
        'primary-fixed': '#99CC99',
        'primary-fixed-dim': '#6DB36D',
        'primary-container': '#153615',
        'on-primary': '#E6E6D5',
        'on-primary-container': '#A8D5A8',
        'on-primary-fixed': '#0a1e0a',
        'on-primary-fixed-variant': '#2a5c2a',
        'inverse-primary': '#2d6b2d',
        'secondary': '#E53935',
        'secondary-fixed': '#EF5350',
        'secondary-fixed-dim': '#E53935',
        'secondary-container': '#730303',
        'on-secondary': '#E6E6D5',
        'on-secondary-fixed': '#2e0000',
        'on-secondary-fixed-variant': '#5c0000',
        'on-secondary-container': '#E57373',
        'tertiary': '#8A8A7A',
        'tertiary-fixed': '#C0C0B0',
        'tertiary-fixed-dim': '#8A8A7A',
        'tertiary-container': '#1a1a14',
        'on-tertiary': '#E6E6D5',
        'on-tertiary-fixed': '#1a1a14',
        'on-tertiary-fixed-variant': '#2d2d22',
        'on-tertiary-container': '#C0C0B0',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#4a4a3a',
        'outline-variant': '#2d2d22',
        'background': '#000000',
        'on-background': '#E6E6D5',
        'on-surface': '#E6E6D5',
        'on-surface-variant': '#AEAE9F',
        'inverse-surface': '#E6E6D5',
        'inverse-on-surface': '#111111',
        'surface-tint': '#6DB36D',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
