/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#000000',
        'surface-dim': '#000000',
        'surface-bright': '#1f1f1f',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#0a0a0a',
        'surface-container': '#111111',
        'surface-container-high': '#1a1a1a',
        'surface-container-highest': '#242424',
        'surface-variant': '#242424',
        'primary': '#A63D4A',
        'primary-fixed': '#C9A0A5',
        'primary-fixed-dim': '#A63D4A',
        'primary-container': '#3B0C0C',
        'on-primary': '#F5EAEA',
        'on-primary-container': '#E8C4C4',
        'on-primary-fixed': '#1A0808',
        'on-primary-fixed-variant': '#3D1414',
        'inverse-primary': '#7A2832',
        'secondary': '#9E1B1B',
        'secondary-fixed': '#C85A5A',
        'secondary-fixed-dim': '#9E1B1B',
        'secondary-container': '#730303',
        'on-secondary': '#E6E6D5',
        'on-secondary-fixed': '#2e0000',
        'on-secondary-fixed-variant': '#5c0000',
        'on-secondary-container': '#E8A8A8',
        'tertiary': '#8A8A7A',
        'tertiary-fixed': '#C0C0B0',
        'tertiary-fixed-dim': '#8A8A7A',
        'tertiary-container': '#1a1a14',
        'on-tertiary': '#E6E6D5',
        'on-tertiary-fixed': '#1a1a14',
        'on-tertiary-fixed-variant': '#2d2d22',
        'on-tertiary-container': '#C0C0B0',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#4a4a3a',
        'outline-variant': '#2d2d22',
        'background': '#000000',
        'on-background': '#E6E6D5',
        'on-surface': '#E6E6D5',
        'on-surface-variant': '#AEAE9F',
        'inverse-surface': '#E6E6D5',
        'inverse-on-surface': '#111111',
        'surface-tint': '#8B2329',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
